### ISSUE TITLE
Refresh event should be invoked even if autoRefresh is disabled

### ISSUE THREAD

**Issue by jangolano** [salte-auth/salte-auth#225]
### Description
It would be nice to notify users that prior to them being logged out that their session is about to be terminated.  Allow for the configuration to take a number of minutes and a function to call.

### Expected outcome
A user of this library can pass in number of minutes prior to expiration.  A passed in function will be called so a client action can be triggered.

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Safari 10
- [X] Safari 9
- [X] Safari 8
- [X] Safari 7
- [X] Edge
- [X] IE 11
- [X] IE 10

**Comment by cecilia-sanare** [comment]
**Moved from https://github.com/salte-io/salte-auth/pull/226**

A lot of this code already exists in `salte-auth`.

https://github.com/salte-io/salte-auth/blob/master/src/salte-auth.js#L667-L680

**All we need to do is the following:**

* add a `refresh` event
* make some minor tweaks to the `setTimeout` function so that `autoRefresh` still calls the refresh event
* add the ability to customize the `refreshToken` buffer (this is currently set to one minute)

**Something like the following should work:**

```js
  // ...
  $$refreshToken() {
    if (this.$timeouts.refresh !== undefined) {
      clearTimeout(this.$timeouts.refresh);
    }

    this.$timeouts.refresh = setTimeout(() => {
      // Allow Auto Refresh to be disabled.
      if (this.$config.autoRefresh) {
          this.refreshToken().catch((error) => {
            console.error(error);
          });
      }

      this.$fire('refresh');
      // We need to default `autoRefreshBuffer` to 60000 in the constructor.
    }, Math.max((this.profile.userInfo.exp * 1000) - Date.now() - this.$config.autoRefreshBuffer, 0));
  }
  // ...
```

Overall I think its a great idea! 
It allows developers to disable the `autoRefresh` functionality, while still giving them a hook into it!

**Comment by cecilia-sanare** [comment]
**Moved from https://github.com/salte-io/salte-auth/pull/226**

Just as a followup. Usage of the above would look like this.

```js
const auth = new SalteAuth({
  // ...
});

// This will happen post refresh, or when a refresh is requested if `autoRefresh` is disabled.
auth.on('refresh', () => {
  // Handle refresh logic here...
});
```

**Comment by cecilia-sanare** [comment]
**Moved from https://github.com/salte-io/salte-auth/pull/226 originally posted by @kpitzen**

@cecilia-sanare We shouldn't still expect the refresh to bail, correct? What would you consider to be working test criteria for this feature?  Just that the token didn't refresh?

**Comment by cecilia-sanare** [comment]
I'd expect the `refreshToken` (not to be confused with `$$refreshToken`) function to not 
be invoked and expect a listener registered via `on('refresh', callback)` to be invoked.

However we should make sure its only invoked once, as `$$refreshToken` already calls `$fire('refresh')`.

**Comment by kpitzen** [comment]
@cecilia-sanare I missed the last part of your comment there.  I think I should wrap the event firing in an else block.  Would that make sense?
