### ISSUE TITLE
Calling salte.auth.refreshToken() not working in Edge Browser

### ISSUE THREAD

**Issue by jangolano** [salte-auth/salte-auth#280]
### Description
Calling salte.auth.refreshToken() is not working within Edge Browser

### Expected outcome

The token should be refreshed

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 11
- [ ] Safari 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [X] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by cecilia-sanare** [comment]
Edge does indeed throw an error when we refresh the id token via `refreshToken` however the id token is updated like we'd expect it to be.

It does seem like the documentation for `refreshToken` is a bit confusing (beyond just the name) since it claims it will refresh all of the user's tokens, rather then just the id token.
