### ISSUE TITLE
login and logout events don't fire in time for `loginWithRedirect`

### ISSUE THREAD

**Issue by pherrmann** [salte-auth/salte-auth#338]
### Description
I'm not sure how to detect a login error occurred using loginWithRedirect without using redirectLoginCallback. https://github.com/salte-io/salte-auth/blob/master/src/salte-auth.js#L222

Unlike loginWithPopup, the on instance method or window login event won't fire due to the browser redirects. http://bit.ly/salte-auth-on

redirectLoginCallback does work, but now returns a deprecation warning. 

- Is there a different way to handle this right now using 2.x?
- Will there be a different way to handle loginWithRedirect errors in 3.x?

Thanks!

### Steps to reproduce
1. I'm testing with 2.11.6, but not sure it matters
2. Perform loginWithRedirect with no redirectLoginCallback
3. Simulate any error. I just returned an error from the profile's validate function. https://github.com/salte-io/salte-auth/blob/master/src/salte-auth.profile.js#L280

**Comment by cecilia-sanare** [comment]
Hey Phil!

This looks to be a bug in the implementation of `loginWithRedirect`.
My guess is the root cause is the following snippets.

_Hey, we errored. Let's clear out our state and whatnot!_
https://github.com/salte-io/salte-auth/blob/6223e22266ca81bc8612224cc75bb255115d74cb/src/salte-auth.js#L148

_That was smart, we cleared out the action as well!_
https://github.com/salte-io/salte-auth/blob/6223e22266ca81bc8612224cc75bb255115d74cb/src/salte-auth.js#L160-L164

### Live Demo

https://glitch.com/edit/#!/knowledgeable-day?path=index.html:34:23

### Q&A

**Is there a different way to handle this right now using 2.x?**

Until this issue is resolved just keep using `redirectLoginCallback`.
That functionality won't be removed until `3.0.0`.

**Will there be a different way to handle `loginWithRedirect` errors in 3.x?**

The reasoning for the deprecation message was to give users a heads up that certain functionality would be deprecated in favor of a new API.

That API is the `on` and `off` functions.

3.x will continue to use these Public APIs however registering could potentially look a little different.

```js
// NOTE: This syntax isn't final!
import { SalteAuth } from '@salte-auth/salte-auth';
import { Auth0 } from '@salte-auth/auth0';
import { Redirect } from '@salte-auth/redirect';

const auth = new SalteAuth({
  // ...

  providers: [
    new Auth0({
      name: 'auth0', // this is the default name
      clientID: '12345',
      routes: true // this lets salte-auth know that all routes are secured for this provider.
    })
  ],

  handlers: [
    new Redirect({
      default: true
    })
  ]
});

// This catches login events from any provider!
auth.on('login', (error) => {
  if (error) console.error(error);
});

// This catches login events from the Auth0 Provider only!
auth.provider('auth0').on('login', (error) => {
  if (error) console.error(error);
});
```

**Comment by pherrmann** [comment]
Hi Ceci!

Thanks for the quick response. I spent some time with the latest update this afternoon and found the login event does fire on redirect.

However, I'm finding a different timing issue with an Angular SSO app that immediately logins when the app loads if its not authenticated. This app is making another login call before the "setTimeout" code that fires the login event can run.

I found checking for the 'login' action before attempting to login prevents getting into a login loop. I'm not sure if $actions and $localState are intended to be publicly accessible, so this may be a risky way to handle this.

```Javascript
get authenticating() {
  return (this.auth.profile.$actions(this.auth.profile.$localState) === 'login');
}
````
Do you have any thoughts on this? Maybe add a public boolean property/method to check if a login is currently in progress?

Thanks!

**Comment by cecilia-sanare** [comment]
Out of curiosity, are you checking the following before invoking `loginWithRedirect` manually?

```js
// ...

if (auth.profile.idTokenExpired) {
  auth.loginWithRedirect();
}
```

Regardless, I think adding a `boolean` or a `string` that reflects the current login status would be a huge plus.

**Comment by pherrmann** [comment]
Yes, I am. After resetting everything from scratch, I'm not having the issue I reported yesterday. So false alarm there.

I am experiencing a minor timing issue where an api call is being made before the endpoint interceptors are added. I was seeing this in the previous version as well, so it's not a new issue. The good news is my app is behaving as it was previously without using the deprecated redirectLoginCallback.
   
Scenario:
- The redirect url makes a secured api call
- While the app is loading during a successful login, the app's check for "is logged in" passes because the token is in session storage. However, the login event hasn't been fired, 
- The app proceeds to render the page which includes making an api call which fails due to no auth header
- The setTimeout() code executes, login event fires, and navigate gets called
- The app reloads again and everything works out fine.

The impact is minimal, but results in a failed api call during the redirect login process. I don't see a convenient way to check if the redirect login is truly in progress.

Thanks again for your help!

**Comment by cecilia-sanare** [comment]
I was sitting here for a while attempting to figure out how in the world that could be happening.

Since the interceptors lock all requests to secured endpoints until an access token is retrieved.

https://github.com/salte-io/salte-auth/blob/1bf41a8594e6add935a1c7fc7bdc060ac62c99fe/src/salte-auth.js#L170-L177

Then I remembered that code never gets run if it detects a redirect.
I've opened #340 to track this issue.
