### ISSUE TITLE
Unable to set extra params or custom endpoint urls

### ISSUE THREAD

**Issue by mikey0000** [salte-auth/salte-auth#344]
### Description

providerUrl: 'https://blah.co.nz/adfs/',
### Expected outcome
https://blah.co.nz/adfs/oauth2/authorize'
### Actual outcome
https://blah.co.nz/oauth2/authorize

shortens the URL 

### Steps to reproduce
self explainatory

also there seems to be no way to add extra query params e.g. &resource=....

**Comment by cecilia-sanare** [comment]
Hey @mikey0000 thanks for taking the time to share your issue with us!

I'm currently unable to reproduce your issue since in the example 
below I'm getting the url you'd expect.

https://glitch.com/edit/#!/vanilla-expansion?path=index.html:10:15

**Just a couple of questions that might help clarify where the issue resides:**

- Is this an `on-prem` ADFS instance or is it provided by `Azure`?
- What do you have the `provider` configured to?

### Extra Query Params

Salte Auth actually does support extra query parameters! 
However, for some reason it looks like it isn't documented.

I ended up opening an issue to track this (#345). 
However for now here's a simple example.

```js
const auth = new SalteAuth({
  // ...

  queryParams: {
    resource: '12345'
  }
});
```

**Comment by mikey0000** [comment]
Hey awesome that queryParams is supported! Yay, yeah I had it configured pretty much the same. I'll try again, as I was playing around in the console perhaps I did something funny.

Thanks so much for the quick reply. I'll check on this asap

**Comment by cecilia-sanare** [comment]
Alright, let me know if you run into any further issues!

**Comment by mikey0000** [comment]
it is on prem, all working, strange, didn't change anything.... 🤷‍♂️

**Comment by cecilia-sanare** [comment]
Glad to hear it! 

If you run into any more problems or have any questions feel free to open an issue here!
